 - name: functions
   hosts: local
   connection: local
   vars:
   #convert strings to list
    technologies: python,ansible,java
    #convert keypair to list
    tags:
     Application: payment
     env: dev
    #convert list to keypair
    tagslist:
      - key: Application
        value: payment
      - key: env
        value: dev
    var_name: ChanDana
    email: Rebba@Gmail.com
    IP: 234.33.3333.3333
   tasks:
    - name: default variables
      ansible.builtin.debug:
        msg: "Hello,{{ name | default('chandana') }}"
      #convert string to list  
    - name: convert string to list
      ansible.builtin.debug:
        msg: "Technologies are {{ technologies | split(',')}}"
      #convert keypair to list
    - name: convert keypair to list
      ansible.builtin.debug:
        msg: "tags are {{ tags | dict2items }}"
      #convert list to keypair
    - name: convert  list to keypair 
      ansible.builtin.debug:
        msg: "tags are {{ tagslist | items2dict }}"
    - name: convert  name to upper 
      ansible.builtin.debug:
        msg: "Name is {{ var_name | upper }}"
    - name: convert  email to lower 
      ansible.builtin.debug:
        msg: "email is {{ email | lower }}"
    - name: change yaml to json file
      ansible.builtin.set_fact:
        student_yaml: "{{ lookup('file','student.yaml') | from_yaml }}"
    - name: change yaml to json
      ansible.builtin.debug:
        msg: "json: {{ student_yaml | to_json }}"
    - name: copy to file
      ansible.builtin.copy:
        dest: ./student-data.json
        content: "{{ student_yaml | to_nice_json }}"
    - name: check ip is valid or not
      ansible.builtin.debug:
        msg: "ip is : {{ IP | ansible.utils.ipv4 }}"

    - name: pipe command module
      ansible.builtin.command: cat /etc/passwd | grep root
      register: command_output
      ignore_errors: true
    - name: print command output 
      ansible.builtin.debug:
        msg: "{{ command_output }}"

    - name: pipe shell module
      ansible.builtin.shell: cat /etc/passwd | grep root
      register: shell_output
    - name: print shell output 
      ansible.builtin.debug:
        msg: "{{ shell_output }}"

    - name: redirect command module
      ansible.builtin.command: ls -ltr > /tmp/output.txt
      register: redirect_command
      ignore_errors: true
    - name: print command redirect output 
      ansible.builtin.debug:
        msg: "{{ redirect_command }}"
    
    - name: redirect command module
      ansible.builtin.shell: ls -ltr > /tmp/output.txt
      register: redirect_shell
    - name: print redirect shell output 
      ansible.builtin.debug:
        msg: "{{ redirect_shell }}"
     