  - name:"install and start  nginx"
    hosts:frontend
    tasks:
    - name: "install nginx"
      ansible.builtin.package:
        name : install
        state:present
      name :"start service"
      ansible.builtin.service:
      - name : service
        state:started
        enable:yes